### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dsanders11** [github/update-project-action#134]
There's been a lot of changes in `main` since `v2`, but no new releases. A new release to pick up some of those changes like #10 would be good.

cc @benbalter

**Comment by ganhammar** [comment]
Yes, would be nice to get a new version of this action @benbalter, if it is still alive?

**Comment by benbalter** [comment]
Thanks for the nudge! [Created a new release as `v3](https://github.com/github/update-project-action/releases/tag/v3) in case https://github.com/github/update-project-action/pull/11 introduced any unknown breaking changes.
